#https://github.com/sukesh-ak/setup-mosquitto-with-docker
services:
  # mqtt5 eclipse-mosquitto
  mqttb:
    image: eclipse-mosquitto:latest
    container_name: mqttb
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - config:/mosquitto/config:rw
      - data:/mosquitto/data:rw
      - log:/mosquitto/log:rw
    restart: unless-stopped
    #command: ["sleep", "infinity"]

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt-network
